import { describe, it, expect } from 'vitest';

// ---------------------------------------------------------------------------
// Source-level scans via vite ?raw — mirrors the pattern used in
// src/components/TierBadge.test.tsx AC-1 and src/App.test.tsx AC-1.
//
// We deliberately AVOID importing `vite.config.ts` as a module because the
// resolved config depends on the Vite plugin pipeline (defineConfig wraps a
// callable returning a config object, and `vite-plugin-pwa` performs work at
// load time). Reading the file as text and asserting on its source lets the
// test run under vitest/jsdom with no plugin context.
// ---------------------------------------------------------------------------

const VITE_CONFIG_SOURCE_MODULES = import.meta.glob('../../vite.config.ts', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;
const VITE_CONFIG_SOURCE: string =
  VITE_CONFIG_SOURCE_MODULES['../../vite.config.ts'] ?? '';

const LAYOUT_SOURCE_MODULES = import.meta.glob('../routes/Layout.tsx', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;
const LAYOUT_SOURCE: string =
  LAYOUT_SOURCE_MODULES['../routes/Layout.tsx'] ?? '';

// ---------------------------------------------------------------------------
// TASK-021 AC-1: Icons exist with non-trivial encoded size.
//
// We resolve each of the three PWA icons through vite's `?inline` query so
// the asset is base64-encoded into a `data:image/png;base64,…` string at
// build time. This avoids importing `node:fs` / `node:path` (which would
// require `@types/node` in tsconfig.app.json) and keeps the test consistent
// with the rest of this file's vite-native source-scan pattern.
//
// Base64 inflates byte size 4/3 plus the ~22-char `data:image/png;base64,`
// prefix, so a real ≥500-byte PNG resolves to a string of length > 700.
// We assert > 1000 chars to give comfortable headroom while still failing
// loudly on a 0-byte truncation or a ~50-byte text-stub replacement.
//
// Icons are NOT regenerated by this task; this test just pins the
// pre-existing concentric-ring PNGs from scripts/generate-icons.mjs.
// ---------------------------------------------------------------------------

const ICON_INLINE_MODULES = import.meta.glob('../../public/icons/*.png', {
  query: '?inline',
  import: 'default',
  eager: true,
}) as Record<string, string>;

const REQUIRED_ICONS = [
  '../../public/icons/icon-192.png',
  '../../public/icons/icon-512.png',
  '../../public/icons/icon-512-maskable.png',
] as const;

describe('TASK-021 AC-1: PWA icons exist with non-trivial encoded size', () => {
  it.each(REQUIRED_ICONS)(
    'TASK-021 AC-1: %s resolves to a base64 PNG data URL longer than 1000 chars',
    (key) => {
      const dataUrl = ICON_INLINE_MODULES[key];
      // kills: vite glob silently failing to resolve the path (file moved,
      // glob pattern stale). Without this guard the length assertion below
      // would throw on `undefined.length` with an unhelpful message.
      expect(dataUrl, `${key} must resolve via import.meta.glob`).toBeDefined();
      // kills: implementer or build script swapping a PNG for a different
      // asset type (SVG, JPEG) — the data URL MIME prefix would change.
      expect(dataUrl?.startsWith('data:image/png')).toBe(true);
      // kills: implementer or build script accidentally truncating the file
      // to a 0-byte placeholder (empty data URL, ~22 chars of prefix only)
      // OR replacing the PNG with a 50-byte "icon coming soon" text stub
      // (data URL would be < 200 chars). Both would technically "exist" but
      // fail the Lighthouse PWA installability check.
      expect((dataUrl ?? '').length).toBeGreaterThan(1000);
    },
  );
});

// ---------------------------------------------------------------------------
// TASK-021 AC-2: Manifest field set is present in vite.config.ts.
//
// We scan the source for each of the seven required field names appearing as
// a property literal (matching either `name:` or `"name":` or `'name':`).
// This is a positive assertion that the manifest object configures these
// fields — a missing field would fail this test even before AC-7 pins values.
// ---------------------------------------------------------------------------

const REQUIRED_MANIFEST_FIELDS = [
  'name',
  'short_name',
  'description',
  'theme_color',
  'background_color',
  'display',
  'orientation',
] as const;

describe('TASK-021 AC-2: vite.config.ts manifest contains all seven required field names', () => {
  it('TASK-021 AC-2: vite.config.ts source was loaded (guards against silent empty-string)', () => {
    // kills: vite ?raw glob silently resolving to an empty string (wrong
    // relative path, file moved). All the substring assertions below would
    // vacuously pass on an empty string without this guard.
    expect(VITE_CONFIG_SOURCE.length).toBeGreaterThan(0);
  });

  it.each(REQUIRED_MANIFEST_FIELDS)(
    'TASK-021 AC-2: manifest declares the %s field',
    (field) => {
      // Match `field:` or `"field":` or `'field':` to allow ESM shorthand and
      // either quoting style. The trailing colon guards against accidental
      // substring matches inside strings (e.g. "name" appearing in a comment).
      const propRegex = new RegExp(`(?:["']${field}["']|\\b${field})\\s*:`);
      // kills: implementer (or future refactor) dropping a field — the AC
      // names all seven, and Lighthouse PWA requires each one for a passing
      // installability score.
      expect(propRegex.test(VITE_CONFIG_SOURCE)).toBe(true);
    },
  );
});

// ---------------------------------------------------------------------------
// TASK-021 AC-7: Manifest field values are PRD-aligned.
//
// Asserts the exact string values for the six pinned fields and a non-empty
// constraint for `description` (implementer may tune the copy).
// ---------------------------------------------------------------------------

describe('TASK-021 AC-7: manifest field values match PRD', () => {
  it('TASK-021 AC-7: name === "Gold List Plus"', () => {
    // Match either `name: 'Gold List Plus'` or `name: "Gold List Plus"`.
    // kills: implementer renaming to "GoldListPlus" or "Gold List+" — the
    // install banner / app launcher uses `name` verbatim and PRD pins the
    // canonical product name.
    const re = /\bname\s*:\s*['"]Gold List Plus['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-7: short_name === "GoldList+"', () => {
    // kills: implementer setting short_name to "Gold" or "GoldList" — Android
    // home-screen icons truncate visibly at ~12 chars, the "+" is meaningful.
    const re = /\bshort_name\s*:\s*['"]GoldList\+['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-7: description is present with a non-empty string literal', () => {
    // Capture the value between quotes. Allows implementer-tuned copy as long
    // as it is at least one character.
    // kills: implementer leaving an empty string (`description: ''`) — passes
    // a naive "field present" check but fails Lighthouse a11y / installability.
    const re = /\bdescription\s*:\s*['"]([^'"]*)['"]/;
    const match = VITE_CONFIG_SOURCE.match(re);
    expect(match, 'description must be a string literal').not.toBeNull();
    expect((match as RegExpMatchArray)[1]?.length ?? 0).toBeGreaterThan(0);
  });

  it('TASK-021 AC-7: theme_color === "#D4AF37" (PRD §4 Gold border colour)', () => {
    // kills: implementer using lowercase hex, a different gold shade, or the
    // bronze/silver hex by mistake. PRD §4 pins this exact value as the OS
    // theming colour so the install splash matches the in-app Gold tier.
    const re = /\btheme_color\s*:\s*['"]#D4AF37['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-7: background_color === "#0b0b0c"', () => {
    // kills: implementer using #000 or #111 — the splash background must
    // match the in-app neutral-950 backdrop, and PRD pins this value so a
    // designer audit doesn't have to chase drift.
    const re = /\bbackground_color\s*:\s*['"]#0b0b0c['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-7: display === "standalone"', () => {
    // kills: implementer using "fullscreen" (hides status bar — bad UX on
    // mobile review screens) or "minimal-ui" (defeats the install-as-app
    // intent of a PWA).
    const re = /\bdisplay\s*:\s*['"]standalone['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-7: orientation === "any"', () => {
    // kills: implementer pinning to "portrait" or "portrait-primary" — would
    // lock out tablet / desktop users in landscape, which the app supports.
    const re = /\borientation\s*:\s*['"]any['"]/;
    expect(re.test(VITE_CONFIG_SOURCE)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// TASK-021 AC-8: <UpdatePrompt/> is mounted in Layout.tsx.
//
// Source-level scan asserts Layout imports UpdatePrompt AND references it as
// a JSX element. Two checks are required because an import without a JSX
// reference is dead code (Layout would not actually render the toast).
// ---------------------------------------------------------------------------

describe('TASK-021 AC-8: <UpdatePrompt/> mounted in Layout.tsx', () => {
  it('TASK-021 AC-8: Layout.tsx source was loaded (guards against silent empty-string)', () => {
    // kills: vite ?raw glob silently resolving to an empty string (file moved,
    // path wrong).
    expect(LAYOUT_SOURCE.length).toBeGreaterThan(0);
  });

  it('TASK-021 AC-8: Layout.tsx imports UpdatePrompt from ../components/UpdatePrompt', () => {
    // Match any import shape that brings in UpdatePrompt. Permit a default or
    // named import from either `../components/UpdatePrompt` (current shape)
    // or a barrel-style `../components` if the codebase ever introduces one.
    // kills: implementer adding a JSX `<UpdatePrompt/>` reference without
    // importing the symbol — TypeScript would catch this, but the test pins
    // the contract independently.
    const importRegex =
      /import\s+(?:\{[^}]*\bUpdatePrompt\b[^}]*\}|UpdatePrompt)\s+from\s+['"][^'"]*UpdatePrompt['"]/;
    expect(importRegex.test(LAYOUT_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-8: Layout.tsx references <UpdatePrompt as a JSX element', () => {
    // kills: implementer importing UpdatePrompt but never rendering it (dead
    // import). The whole point of mounting in Layout is that the toast is
    // reachable from every screen — an unrendered import accomplishes nothing.
    const jsxRegex = /<UpdatePrompt\b/;
    expect(jsxRegex.test(LAYOUT_SOURCE)).toBe(true);
  });

  it('TASK-021 AC-8: Layout.tsx renders <UpdatePrompt exactly once (not duplicated)', () => {
    // kills: implementer accidentally pasting <UpdatePrompt/> twice (would
    // mount two toasts and call useRegisterSW twice — Workbox tolerates this
    // but the user sees double).
    const occurrences = LAYOUT_SOURCE.match(/<UpdatePrompt\b/g) ?? [];
    expect(occurrences.length).toBe(1);
  });
});
